djangoLevelFive/LoginPage/LoginPage/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('basic_app/', include('basic_app.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('admin/', admin.site.urls),
]

djangoLevelFive/LoginPage/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns=[
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('special_page/', views.special_page, name='special_page'),
]

djangoLevelFive/LoginPage/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE)

    #additional fields
    protfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(blank=True, upload_to='profile_pic')

    def __str__(self):
        return self.user.username

djangoLevelFive/LoginPage/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('protfolio_site', 'profile_pic')

djangoLevelFive/LoginPage/basic_app/views.py
from django.shortcuts import render
from basic_app import forms

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from  django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

def register(request):

# Check for registeration
    registered = False

    if request.method == "POST":
        user_form = forms.UserForm(request.POST)
        profile_form = forms.UserProfileInfoForm(request.POST)

        # Validate data
        if user_form.is_valid() and profile_form.is_valid():

            # save user data in User table
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            # Mapping of user in profile model
            profile = profile_form.save(commit=False)
            profile.user = user

            # Check if profile pic is provided
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = forms.UserForm()
        profile_form = forms.UserProfileInfoForm()

    contex_dict={'user_form':user_form,
                'profile_form':profile_form,
                'registered':registered}

    return render(request, 'basic_app/register.html', contex_dict)

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('<h1>OPP you seems to be inactive from very long time</h1>')
        else:
            return HttpResponse('<H1> Well username:{} and password:{} is wrong'.format(username,password))
    else:
        return render(request, 'basic_app/user_login.html', {})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special_page(request):
    return HttpResponse('<h1>This page required login ....</h1>')

djangoLevelFive/LoginPage/templates/basic_app/base.html
<!DOCTYPE HTML>
<HTML>
<head>
    <Title>
        {% block title_block %}
        {% endblock %}
    </Title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="navbar-collapse collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item"><a class='navbar-brand' href="{% url 'index'%}">DJANGO</a></li>
            <li class="nav-item"><a class='nav-link' href="{% url 'admin:index'%}">Admin</a></li>
            <li class="nav-item"><a class='nav-link' href="{% url 'basic_app:register'%}">Register</a> </li>
            {% if user.is_authenticated %}
                <li class="nav-item"><a class='nav-link' href="{% url 'logout'%}">Logout</a> </li>
            {% else %}
                <li class="nav-item"><a class='nav-link' href="{% url 'basic_app:user_login'%}">Login</a> </li>
            {% endif %}
            <li class="nav-item"><a class='nav-link' href="{% url 'basic_app:special_page'%}">Special Page</a> </li>
        </ul>
    </div>
</nav>

<div class="jumbotron">
    {% block body_block %}
    <!--        FILL ALL THE STUFF HERE USING INHERITANCE-->
    {% endblock %}
</div>
</body>
</HTML>

djangoLevelFive/LoginPage/templates/basic_app/index.html
<!DOCTYPE HTML>
{% extends 'basic_app/base.html' %}
{% block title_block %}
INDEX_PAGE
{% endblock %}
{% block body_block %}
    <h1>WELCOME TO INDEX Page</h1>
    <h1>Go to Register Tab for Registration</h1>
{% endblock %}

djangoLevelFive/LoginPage/templates/basic_app/register.html
<!DOCTYPE HTML>
{% extends 'basic_app/base.html' %}
{% load static %}
    {% block body_block %}
        <div class = container>
            {% if registered %}
                <h1>ThankYou for registeration </h1>
            {% else %}
                <h1>WELCOME TO REGISTRATION PAGE</h1>
                <h3>Please fill the below details:-</h3>
                <form enctype="multipart/form-data" method='POST'>
                    {% csrf_token %}
                    {{ user_form.as_p }}
                    {{ profile_form.as_p }}
                    <input name="" value="Register" type="submit">
                </form>
            {% endif %}
        </div>
    {% endblock %}

djangoLevelFive/LoginPage/templates/basic_app/user_login.html
<!DOCTYPE HTML>
{% extends 'basic_app/base.html' %}
{% block body_block %}
    <h1>Plese login below!</h1>

    <form action="{% url 'basic_app:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username: </label>
        <input type="text" name="username" aria-placeholder="Enter UserName">
        <label for="password">Password: </label>
        <input type="password" name="password" aria-placeholder="Enter Password">
        <input type="submit" name="Login" value="Login">
    </form>

{% endblock %}